spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/DatingBureau
    username: SKELETON
    password: 123
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:
    hiddenmethod:
      filter:
        enabled: true
